# Jekyll configuration

remote_theme: streetturtle/jekyll-clean-dark

name: grndkntrl
description: Tinkerer

# Url is currently only used only for the RSS feed in feed.xml
url: http://grndkntrl.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: grndkntrl
copyright: 1979-20XX

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: false

social:
  github: grndkntrl
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
#yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: grndkntrl
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
